
version: 2
updates:
    - package-ecosystem: "docker"
      directory: "/"
      target-branch: main
      schedule:
        interval: "weekly"
      groups:
        docker-deps:
          patterns:
            - "*"