
version: 2
updates:
  - package-ecosystem: "pip" # See documentation for possible values
    directory: "/" # Location of package manifests
    target-branch: main
    schedule:
      interval: "weekly"
    groups:
      pip-deps:
        patterns:
          - "*"
  # Enable version updates for Docker
  - package-ecosystem: "docker"
    # Look for a `Dockerfile` in the `root` directory
    directory: "/"
    target-branch: main
    # Check for updates once a week
    schedule:
      interval: "weekly"