#!/bin/bash
set -e

# Install Python packages that aren't available via APT
if [ "$1" = "configure" ]; then

    echo "Create virtual environment for application"
    cd "/opt/starwit/videosource"
    python3 -m venv .venv
    source .venv/bin/activate
    pip install -r requirements.txt 

    echo "Create wrapper script"
    mkdir -p /usr/local/bin
    cat > /usr/local/bin/videosource <<EOF
#!/bin/bash

current_dir=$PWD
cd /opt/starwit/videosource
source .venv/bin/activate

python3 main.py "\$@"
cd $current_dir
EOF
    chmod +x /usr/local/bin/videosource    

    # link settings file from etc
    cd /opt/starwit/videosource
    ln -s /etc/starwit/videosource/settings.yaml settings.yaml

    systemctl daemon-reload
    systemctl start videosource.service        
    systemctl enable videosource.service
fi

#DEBHELPER#

exit 0