#!/bin/bash
set -e

if [ "$1" = "remove" ] || [ "$1" = "purge" ]; then

    # Stop the service
    systemctl stop videosource.service

    # Disable the service
    systemctl disable videosource.service

    # Remove the service file
    rm -f /etc/systemd/system/videosource.service

    systemctl daemon-reload

    # Remove the wrapper script
    rm -f /usr/local/bin/videosource
    
    # Remove application directory
    rm -rf /opt/starwit/videosource

    # Remove config files directory
    rm -rf /etc/starwit/videosource
fi

#DEBHELPER#

exit 0