name: Build latest APT package

on:
  workflow_dispatch:
  pull_request:

jobs:
  build:
    name: package APT
    runs-on: [self-hosted, linux, X64]
    container:
        image: starwitorg/debian-packaging:0.0.1
        volumes:
            - ./:/code

    steps:
      - name: checkout
        uses: actions/checkout@v2
      - name: build package
        run: |
            export PATH=/root/.local/bin/:$PATH
            cd /code
            make
