name: Build and release latest APT package

on:
  workflow_dispatch:
  pull_request:

permissions:
  contents: write

jobs:
  build:
    name: package APT
    runs-on: [self-hosted, linux, X64]
    container:
        image: starwitorg/debian-packaging:0.0.1
        volumes:
            - ./:/code

    steps:
      - name: checkout
        uses: actions/checkout@v4
      - name: build package
        run: |
            export PATH=/root/.local/bin/:$PATH
            cd /code
            echo "export GPG_KEY=${GPG_KEY}" > env.sh
            echo "export PASSPHRASE=${GPG_KEY}" >> env.sh
            cat env.sh
            source --help
            source ./env.sh
            make
            echo "VERSION=$(poetry version -s)" >> $GITHUB_ENV
        env:
          PASSPHRASE: ${{ secrets.OSSRH_GPG_SECRET_KEY_PASSWORD }}
          GPG_KEY: ${{ secrets.OSSRH_GPG_SECRET_KEY }}
      - name: create release
        run: |
         echo "Releasing package with version ${VERSION}"
         find ./target
         gh release create ${VERSION} ./target/*deb
        env:
          GH_TOKEN: ${{ github.token }}