name: Build and release latest APT package

on:
  workflow_dispatch:
  pull_request:

env:
    GH_TOKEN: ${{ github.token }}   

jobs:
  build:
    name: package APT
    runs-on: [self-hosted, linux, X64]
    container:
        image: starwitorg/debian-packaging:0.0.1
        volumes:
            - ./:/code

    steps:
      - name: checkout
        uses: actions/checkout@v4
      - name: build package
        run: |
            export PATH=/root/.local/bin/:$PATH
            cd /code
            make
            echo "VERSION=$(poetry version -s)" >> $GITHUB_ENV
      - name: create release
        run: |
         echo "Releasing package with version ${VERSION}"
         gh --version
         gh release create ${VERSION} ./target/*deb