name: PR build

on:
  workflow_dispatch:
  pull_request:

permissions:
  contents: write

jobs:
  build:
    name: package APT
    runs-on: [self-hosted, linux, X64]
    container:
        image: starwitorg/debian-packaging:0.0.2
        env:
          PASSPHRASE: ${{ secrets.OSSRH_GPG_SECRET_KEY_PASSWORD_FLAT }}
          GPG_KEY: ${{ secrets.OSSRH_GPG_SECRET_KEY_B64 }}          
        volumes:
            - ./:/code

    steps:
      - name: checkout
        uses: actions/checkout@v4
      - name: build apt package
        run: |
            export PATH=/root/.local/bin/:$PATH
            bash -c ./start_make.sh
            echo "VERSION=$(poetry version -s)" >> $GITHUB_ENV
      - name: test poetry builds
        run: |
            export PATH=/root/.local/bin/:$PATH
            poetry lock
            poetry install
